#:tombi schema.strict = false
#:schema https://mise.jdx.dev/schema/mise.json

[settings]
activate_aggressive = true
color_theme = "catppuccin"
experimental = true
trusted_config_paths = ["~/.local/share/chezmoi", "~/ghq"]
install_before = "12h"
pin = true
lockfile = true
task.monorepo_depth = 2
cargo.binstall = true
npm.package_manager = "bun"
pipx.uvx = true
github.credential_command = "gh auth token"

# For Renovate:
# - Use short names if available (node, aws-cli), otherwise full names (aqua:peco/peco, npm:sfw)
#   https://docs.renovatebot.com/modules/manager/mise/#supported-default-registry-tool-short-names
#   https://mise.jdx.dev/registry.html#tools
# - Specify versions ("1.2.3") if Renovate recognizes them, otherwise "latest"
#   https://docs.renovatebot.com/modules/manager/mise/#limitations
[tools]
node = "24.15.0"
deno = "2.7.12"
bun = "1.3.12"
rust = "1.95.0"
go = "1.26.2"
python = "3.14.4"
uv = "0.11.7"
shellcheck = "0.11.0"
shfmt = "3.13.1"
jq = "1.8.1"
yq = "4.53.2"
aws-cli = { version = "2.34.32", symlink_bins = "true" }
"aqua:ast-grep/ast-grep" = "0.42.1"
"aqua:sharkdp/fd" = "10.4.2"
"aqua:junegunn/fzf" = "0.71.0"
"aqua:ByteNess/aws-vault" = "7.10.1"
"aqua:rhysd/actionlint" = "1.7.12"
"aqua:XcodesOrg/xcodes" = "1.6.2"
"aqua:sharkdp/bat" = "0.26.1"
"aqua:peco/peco" = "0.6.0"
"aqua:BurntSushi/ripgrep" = "15.1.0"
"aqua:cli/cli" = "2.90.0"
"aqua:x-motemen/ghq" = "1.10.1"
"aqua:dandavison/delta" = "0.19.2"
"aqua:Wilfred/difftastic" = "0.68.0"
"aqua:jesseduffield/lazygit" = "0.61.1"
"aqua:anomalyco/opencode" = "1.14.18"
"aqua:openai/codex" = "0.121.0"
"aqua:github/copilot-cli" = "1.0.33"
"aqua:github/copilot-language-server-release" = "1.473.0"
"aqua:k1LoW/git-wt" = "0.27.0"
"aqua:tree-sitter/tree-sitter" = "0.26.8"
"aqua:suzuki-shunsuke/pinact" = "3.9.0"
"npm:npm-check" = "6.0.1"
"npm:sfw" = "2.0.4"
"npm:@mermaid-js/mermaid-cli" = "11.12.0"
"pipx:pfnet/plamo-translate-cli" = { version = "1.0.5", uvx_args = "-p 3.12" }
"github:h3y6e/cxg" = "2026.4.5"
"github:h3y6e/skills" = "2026.4.4"
