#:tombi schema.strict = false
#:schema https://mise.jdx.dev/schema/mise.json

[bootstrap.packages]
"brew:aria2" = "latest"
"brew:chezmoi" = "latest"
"brew:git" = "latest"
"brew:gnupg" = "latest"
"brew:libyaml" = "latest"
"brew:mas" = "latest"
"brew:pinentry-mac" = "latest"
"brew:watchman" = "latest"

[settings]
activate_aggressive = true
cargo.binstall = true
color_theme = "catppuccin"
experimental = true
github.use_git_credentials = true
lockfile = true
minimum_release_age = "1d"
npm.package_manager = "aube"
pin = true
pipx.uvx = true
task.monorepo_depth = 2

[settings.status]
show_env = true
show_tools = true

# For Renovate:
# - Use short names if available (node, aws-cli), otherwise full names (aqua:peco/peco, npm:sfw)
#   https://docs.renovatebot.com/modules/manager/mise/#supported-default-registry-tool-short-names
#   https://mise.jdx.dev/registry.html#tools
# - Specify versions ("1.2.3") if Renovate recognizes them, otherwise "latest"
#   https://docs.renovatebot.com/modules/manager/mise/#limitations
[tools]
actionlint = "1.7.12"
"aqua:ByteNess/aws-vault" = "7.12.5"
"aqua:docker/buildx" = "0.35.0"
"aqua:k1LoW/git-wt" = "0.29.0"
ast-grep = "0.44.1"
aube = "1.26.0"
aws-cli = { version = "2.35.16", symlink_bins = "true" }
bat = "0.26.1"
bun = "1.3.14"
cargo-binstall = "1.20.1"
checkov = "3.3.6"
claude-code = "2.1.202"
codex = "latest"
colima = "0.10.3"
copilot-cli = "1.0.68"
cosign = "3.1.1"
delta = "0.19.2"
deno = "2.9.1"
difftastic = "0.69.0"
direnv = "2.37.1"
docker-cli = "29.6.1"
docker-compose = "5.3.0"
fd = "10.4.2"
ffmpeg = "8.1.1"
fzf = "0.74.0"
gcloud = "572.0.0"
gh = "2.96.0"
ghalint = "1.5.6"
"github:h3y6e/anna" = "2026.6.0"
"github:h3y6e/cxg" = "2026.6.0"
ghq = "1.10.1"
go = "1.26.4"
hadolint = "2.14.0"
hk = "1.50.0"
imagemagick = "7.1.2_25"
java = "26.0.1"
jj = "0.43.0"
jq = "1.8.2"
lazygit = "0.63.0"
lima = "2.1.4"
"llama.cpp" = { version = "9893", version_prefix = "b" }
neovim = "0.12.4"
node = "26.4.0"
"npm:@mermaid-js/mermaid-cli" = "11.16.0"
"npm:npm-check" = "6.0.1"
"npm:sfw" = "2.0.6"
ollama = "0.31.1"
opencode = "1.17.14"
peco = "0.6.0"
pi = "0.80.3"
pinact = "4.1.0"
python = "3.14.6"
ripgrep = "15.1.0"
rust = "1.96.1"
shellcheck = "0.11.0"
sheldon = "0.8.5"
shfmt = "3.13.1"
slsa-verifier = "2.7.1"
tree-sitter = "0.26.10"
trivy = "0.72.0"
uv = "0.11.27"
xcodes = "2.0.2"
yq = "4.53.3"
zizmor = "1.26.1"
