#:tombi schema.strict = false
#:schema https://mise.jdx.dev/schema/mise.json

min_version = "2026.10.7"

[settings]
activate_aggressive = true
cargo.binstall = true
color_theme = "catppuccin"
experimental = true
install_layout = "identity"
github.use_git_credentials = true
lockfile = true
minimum_release_age = "1d"
npm.package_manager = "aube"
pin = true
pypi.uvx = true
task.monorepo_depth = 2
tool_update.global_auto = true

[settings.self_update]
auto = true
check_duration = "1d"

[settings.skills]
dir = ".agents/skills"
prune = true

[settings.status]
show_env = true
show_tools = true

# For Renovate:
# - Use short names if available (node, aws-cli), otherwise full names (aqua:peco/peco, npm:sfw)
#   https://docs.renovatebot.com/modules/manager/mise/#supported-default-registry-tool-short-names
#   https://mise.jdx.dev/registry.html#tools
# - Specify versions ("1.2.3") if Renovate recognizes them, otherwise "latest"
#   https://docs.renovatebot.com/modules/manager/mise/#limitations
[tools]
"aqua:docker/buildx" = "0.38.0"
"aqua:k1LoW/git-wt" = "0.30.0"
ast-grep = "0.50.0"
aube = "2.7.0"
aws = { version = "2.37.11", symlink_bins = "true" }
bat = "0.26.1"
bun = "1.4.2"
cargo-binstall = "1.25.2"
chezmoi = "2.73.0"
claude-code = "2.1.295"
codex = "latest"
colima = "0.10.3"
copilot-cli = "1.0.95"
cosign = "3.1.3"
delta = "0.20.1"
deno = "2.9.7"
direnv = "2.38.1"
docker-cli = "29.9.0"
docker-compose = "5.6.0"
fd = "10.5.0"
ffmpeg = "9.0.2"
fzf = "0.74.4"
gcloud = "587.0.0"
gh = "2.102.0"
ghalint = "1.5.6"
ghq = "1.11.2"
go = "1.27.2"
hadolint = "2.15.1"
hk = "2.5.0"
imagemagick = "7.1.2_31"
jactionlint = "1.8.2"
java = "27.0.0"
jj = "0.46.0"
jq = "1.8.2"
lazygit = "0.66.0"
lima = "2.2.1"
"llama.cpp" = { version = "11398", version_prefix = "b" }
neovim = "0.12.6"
node = "26.11.1"
"npm:@krayinc/docbase-cli" = "1.1.4"
"npm:npm-check" = "6.0.1"
"npm:sfw" = "2.0.6"
opencode = "latest"
"packslip:github.com/h3y6e/anna" = "latest"
"packslip:github.com/h3y6e/cxg" = "latest"
peco = "0.6.0"
pi = "1.1.0"
pinact = "5.0.0"
"pypi:huggingface_hub" = { version = "2.2.0", uvx_args = "--python 3.14" }
python = "3.15.0"
ripgrep = "15.2.0"
rust = "1.99.0"
shellcheck = "0.11.0"
sheldon = "0.8.5"
shfmt = "3.14.1"
slsa-verifier = "2.7.1"
tmux = "3.7c"
tree-sitter = "0.27.1"
trivy = "0.75.0"
usage = "6.12.1"
uv = "0.12.24"
xcodes = "2.1.0"
yq = "4.54.1"
zizmor = "1.30.1"
zmx = "0.8.1"
