name: check

on:
  push:

permissions:
  contents: read

env:
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  install:
    runs-on: ubuntu-slim
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - run: ./install.sh -h
      - run: ./install.sh
      - run: mise x chezmoi -- chezmoi data -f yaml

  remote:
    runs-on: ubuntu-slim
    timeout-minutes: 5

    steps:
      - run: bash -c "$(curl -fsSL s.h3y6e.com/dotfiles)"
      - shell: bash -i {0}
        run: cz managed
